### ISSUE TITLE
Change so fields like title and comment are adjustable

### ISSUE THREAD

**Issue by theelectricwiz** [MeldCE/wp-gallery-hierarchy#21]
Change so fields like title and comment are adjustable
- Add ability to delete/add new fields (make it so you can't delete the title and comment, only change the image meta field and whether or not it is saved back to the image [and original remote image when implemented])
- Have fields: field label; image meta field(s); whether to make editable and save data back to image

**Comment by bytesnz** [comment]
complete in 50036ba6f0f8d93acc949ffdea90ebaa41ab41c8
